# 2026-10-03: an array element assignment whose index is an expansion. `map[$key]=v` ran as a
# command ("command not found", element unset) and `m+=(["$k"]=v)` silently set nothing: only an
# index wholly inside the first literal was recognised. Expected output generated by GNU bash
# (WSL Ubuntu).
declare -A st
k=old; st[$k]=5; st[new]=6
for k2 in a b; do st[$k2]=7; done
st["quoted key"]=q; kk="sp ace"; st["$kk"]=sp; st[${k}x]=braced
for key in $(printf '%s\n' "${!st[@]}" | sort); do printf '[%s]=%s ' "$key" "${st[$key]}"; done; echo
declare -a ix; i=2
ix[$i]=x; ix[i+1]=y; ix[$((i+2))]=z; ix[0]=lit
echo "ix: ${ix[*]} (count ${#ix[@]})"
val="v 1"; declare -A m
m+=(["$k"]="$val" [two]=2 [$i]=three)
for key in $(printf '%s\n' "${!m[@]}" | sort); do printf '<%s>=%s ' "$key" "${m[$key]}"; done; echo
declare -a c; c=([$i]=a [i+3]=b)
echo "c: idx=${!c[*]} vals=${c[*]}"
declare -A odd; odd["a]=b"]=x; ok="a]=b"; echo "odd key: ${odd[$ok]}"   # read back via a variable: ${odd["a]=b"]} is a separate read-side defect
w="w1"; count[$w]=1 2>/dev/null; echo "count[\$w] (indexed, w not numeric -> 0): ${count[0]}"
echo "status of a normal array assignment: $(m[$k]=v; echo $?)"
