# 2026-10-05: a background job runs on its own copy of the shell, taken at `&`, as bash forks one.
# It ran on the parent's state: `for f in *; do gzip "$f" & done` read $f after the loop had moved
# on, and a job's `cd` or assignment changed the parent. Expected output generated by GNU bash (WSL).
cd "$(mktemp -d)" || exit 1

# the loop variable is the value at `&`, for builtins and externals alike
for i in 1 2 3; do echo "job $i" > "b$i" & done; wait; cat b1 b2 b3
for i in 1 2 3; do "$BASH" -c 'echo "external $1"' _ "$i" > "e$i" & done; wait; cat e1 e2 e3
f() { echo "function got $1"; }; for i in x y; do f "$i" > "f$i" & done; wait; cat fx fy

# nothing a job sets comes back
n=0; { n=5; echo "in the job n=$n"; } > jn & wait; cat jn; echo "parent n=$n"
mkdir sub; cd sub & wait; [[ $PWD == */sub ]] && echo "parent moved" || echo "parent stayed put"
{ g() { :; }; } & wait; type -t g >/dev/null && echo "function leaked" || echo "function stayed in the job"

# but the job sees what the parent had
v=visible; { echo "job sees v=$v"; } > jv & wait; cat jv

# kill ends an in-process loop, not just the program it is running
while :; do sleep 0.05; done &
kill %1; wait %1; echo "killed loop: $?"
sleep 0.1 & p=$!; wait $p; echo "wait \$!: $?"
