# 2026-10-03 (msp430-a2's report): a copy made without -p is a new file, so its mtime is NOW.
# Windows' CopyFile keeps the source's time, so C#Bash's plain cp did too: a restored
# `cp backup file` looked older than its build outputs, and MSBuild silently kept a stale build.
# Expected output generated by GNU coreutils (WSL Ubuntu).
d=$(mktemp -d); cd "$d" || exit 1
printf x > src; touch -d 2020-01-01 src
fresh() { [ $(( $(date +%s) - $(stat -c %Y "$1") )) -lt 120 ] && echo now || echo "old ($(date -d @"$(stat -c %Y "$1")" +%Y))"; }
cp src a;              echo "cp:                  $(fresh a)"
cp -p src b;           echo "cp -p:               $(fresh b)"
cp -a src c;           echo "cp -a:               $(fresh c)"
cp --preserve src c2;  echo "cp --preserve:       $(fresh c2)"
printf y > o; touch -d 2019-01-01 o; cp src o; echo "cp over an old file: $(fresh o)"
mkdir t; cp src t/;    echo "cp into a directory: $(fresh t/src)"
mkdir -p tree/sub; printf z > tree/sub/f; touch -d 2020-01-01 tree/sub/f
cp -r tree tree2;      echo "cp -r (a file in it): $(fresh tree2/sub/f)"
cp -rp tree tree3;     echo "cp -rp (a file in it): $(fresh tree3/sub/f)"
chmod -w src; cp src ro; echo "cp of a read-only source: $(fresh ro)"
cmp -s src a && echo "contents identical"
cd /; chmod -R u+w "$d" 2>/dev/null; rm -rf "$d"
