# 2026-10-03: CR is data. awk, head, tail, grep, read, mapfile, cut, sort, xargs ... dropped the CR
# of CRLF and ended a line at a lone CR (.NET ReadLine), and the text tools decoded a file starting
# FF FE as UTF-16 and dropped a UTF-8 BOM. Expected output generated by GNU bash + coreutils
# (WSL Ubuntu) from this same script: every probe prints the exact bytes produced.
d=$(mktemp -d)
cd "$d" || exit 1
printf 'a\r\nb\r\nc\n' > crlf.txt          # CRLF lines, last line LF
printf 'x\ry z\n2\r\n' > lone.txt          # a lone CR mid-line
printf 'b\r\na\r\nb\r\n' > dup.txt
printf '\xef\xbb\xbfhello\r\n' > bom8.txt
printf '\xff\xfeAB\nCD\n' > bom16.txt
p() { printf '%-22s' "$1"; od -An -c | tr -s ' ' | tr -d '\n'; echo; }
CR=$(printf '\r')   # kept out of the pipelines below: stage race (DECISIONS 2026-10-03)
cat crlf.txt                    | p cat
awk '{print}' crlf.txt          | p awk
awk '{print $NF}' lone.txt      | p 'awk $NF'
awk -F' ' '{print NF}' lone.txt | p 'awk NF'
head -n 2 crlf.txt              | p head
head -n 1 lone.txt              | p 'head lone'
tail -n 2 crlf.txt              | p tail
grep '' crlf.txt                | p grep
grep -c "$CR" crlf.txt          | p 'grep -c CR'
grep -c '' lone.txt             | p 'grep -c lone'
wc -l < lone.txt                | p 'wc -l lone'
sed -n p crlf.txt               | p sed
cut -c1- crlf.txt               | p cut
sort crlf.txt                   | p sort
uniq dup.txt                    | p uniq
sort -u dup.txt                 | p 'sort -u'
tac crlf.txt                    | p tac
rev crlf.txt                    | p rev
nl -ba crlf.txt                 | p nl
paste crlf.txt crlf.txt         | p paste
comm -12 dup.txt dup.txt        | p comm
tee tee.out < crlf.txt          | p tee
xargs printf '[%s]' < crlf.txt  | p xargs
xargs -I{} printf '<{}>' < crlf.txt | p 'xargs -I'
cat crlf.txt | head -n 2        | p 'pipe|head'
cat crlf.txt | awk '{print}'    | p 'pipe|awk'
cat crlf.txt | grep b           | p 'pipe|grep'
x=$(cat crlf.txt); printf '%s' "$x" | p 'capture'
while IFS= read -r l; do printf '%s|' "$l"; done < crlf.txt | p 'read -r'
while read -r a b; do printf '%s|%s|' "$a" "$b"; done < lone.txt | p 'read -r a b'
mapfile -t arr < crlf.txt; printf '%s|' "${arr[@]}" | p 'mapfile -t'
{ head -n 1; sed -n p; } < crlf.txt | p 'head;sed shared'   # shared stdin: head must leave the rest
{ grep -m1 a; sed -n p; } < crlf.txt | p 'grep -m1;sed shared'
head -n 1 bom8.txt              | p 'head bom8'
grep h bom8.txt                 | p 'grep bom8'
awk '{print}' bom8.txt          | p 'awk bom8'
head -n 1 bom16.txt             | p 'head bom16'
cat bom16.txt | head -n 1       | p 'pipe|head bom16'
head -n 1 < bom16.txt           | p 'head < bom16'
# an EXTERNAL child's bytes (0xFF and a CR) through the routes the shell copies as text:
# `$( )` decoded 0xFF to U+FFFD, and `1>&2` in a captured group escaped to the real stderr
E() { "$BASH" -c 'printf "A\377\r\n"'; }
E | p 'ext pipe'
x=$(E); printf '%s\n' "$x" | p 'ext capture'
x=$( { E 1>&2; } 2>&1 ); printf '%s\n' "$x" | p 'ext 1>&2 group'
cd / && rm -rf "$d"
