# 2026-10-03: each shell has its own working directory. A pipeline stage's `cd` (or a `( cd … )`
# inside a stage) used to move the PROCESS cwd, i.e. every stage and the parent:
# `(cd sub && …) | tee out.log` put out.log in sub/ in 148 of 200 runs, `cd sub | true` moved the
# shell, and an in-process script's `cd` moved its caller. Expected output generated by GNU bash
# (WSL Ubuntu); paths are printed relative to a temp directory so the two runs compare.
d=$(mktemp -d); cd "$d" || exit 1
mkdir -p sub/deeper; echo top > f; echo inner > sub/f
start=$(pwd)
here() { case "$PWD" in "$start") echo .;; "$start"/*) echo "${PWD##*/}";; *) echo elsewhere;; esac; }   # literal pattern: ${PWD#"$start"/} is a separate defect
cd sub | true; echo "after 'cd sub | true': $(here)"
(cd sub && echo "in a subshell: $(here)"); echo "after the subshell: $(here)"
bad=0
for i in 1 2 3 4 5 6 7 8 9 10; do
  rm -f out.log sub/out.log
  (cd sub && echo x) | tee out.log > /dev/null
  { [ -f out.log ] && [ ! -f sub/out.log ]; } || bad=$((bad+1))
done
echo "tee's file misplaced: $bad of 10"
(cd sub && cat f) | cat
echo | { cd sub; cat f; echo "stage cwd: $(here)"; }; echo "parent cwd: $(here)"
(cd sub && echo hi > made.txt) | cat; [ -f sub/made.txt ] && echo "redirect in a cd'd stage: lands in sub" || echo "redirect misplaced"
echo | (cd sub/deeper && touch g1 g2 && for g in g*; do echo "glob: $g"; done)
echo | (cd sub && [ -f f ] && echo "test -f in a cd'd stage: found")
echo | (cd sub && "$BASH" -c 'echo "external child cwd: ${PWD##*/}"')
echo | (cd sub && find . -name f)
echo | (cd sub && { echo "dup redirects in a cd'd stage" 1>&2; } 2>&1 | cat)   # `2>&1`'s "1" is an fd, not a path
printf 'cd deeper\n' > sub/s.sh; chmod +x sub/s.sh 2>/dev/null
cd sub; ./s.sh; echo "after an in-process script that cds: $(here)"; cd ..
echo | (cd sub && ./s.sh; echo "after a script in a stage: $(here)")
cd /; rm -rf "$d"
