d="$TEMP/bash_w3suite"
rm -rf "$d"; mkdir -p "$d/sub"
echo hi > "$d/a.txt"
cp "$d/a.txt" "$d/b.txt"; [ -f "$d/b.txt" ] && echo "cp ok"
mv "$d/b.txt" "$d/c.txt"; { [ -f "$d/c.txt" ] && [ ! -f "$d/b.txt" ]; } && echo "mv ok"
cp -r "$d/sub" "$d/sub2"; [ -d "$d/sub2" ] && echo "cp-r ok"
rm "$d/a.txt"; [ ! -f "$d/a.txt" ] && echo "rm ok"
rm "$d/sub"; [ -d "$d/sub" ] && echo "dir-kept-without-r"
rm -rf "$d"; [ ! -d "$d" ] && echo "rm-rf ok"
