# 2026-10-04: nohup, setsid and disown (goal-2 backlog item 2, option b). Whether a child really
# outlives the shell cannot be checked from inside one script; this pins the visible behaviour.
# Expected output generated by GNU bash + coreutils + util-linux (WSL).
cd "$(mktemp -d)" || exit 1
nohup echo "nohup ran" </dev/null 2>&1; echo "nohup status $?"
nohup sh -c 'exit 7' </dev/null; echo "nohup passes the status: $?"
nohup </dev/null 2>/dev/null; echo "nohup, no operand: $?"
[[ -e nohup.out ]] && echo "nohup.out created" || echo "no nohup.out (stdout is not a terminal)"
setsid echo "setsid ran"; echo "setsid status $?"
setsid sh -c 'exit 3'; echo "setsid passes the status: $?"
disown 2>/dev/null; echo "disown, no job: $?"
sleep 3 & sleep 3 &
jobs > j1; echo "jobs before: $(wc -l < j1)"
disown %1; jobs > j2; echo "after disown %1: $(wc -l < j2)"
disown -a; jobs > j3; echo "after disown -a: $(wc -l < j3)"
disown %9 2>/dev/null; echo "disown, no such job: $?"
