# 2026-10-03: a backslash-escaped glob/brace/tilde character is QUOTED. The lexer dropped the
# escape's quoting, so `echo \*` printed file names and `find . -name \*.txt` received the list of
# matching files instead of the pattern. Expected output generated by GNU bash (WSL Ubuntu).
d=$(mktemp -d); cd "$d" || exit 1
touch a.txt b.txt; mkdir sub; touch sub/c.txt   # no 'x*y': Windows forbids * in file names
echo \*; echo \?; echo \*.txt; echo a\*; echo \[ab\]
find . -name \*.txt | sort
find . -name \*.txt -path ./sub/\* | sort
echo \{a,b\}; echo {a,b}; echo \~; echo a\,b   # {x\,y,z} (an escaped comma inside a live brace) is a known per-field limitation
x=\*; echo "assignment keeps it literal: $x"
case '*' in \*) echo "case: an escaped * is literal";; *) echo "case: wrong";; esac
case 'q' in \*) echo "case: wrong";; *) echo "case: a live * still matches";; esac
[[ 'a*' == a\* ]] && echo "[[ ]]: escaped * matches literally"
[[ ab == a\* ]] || echo "[[ ]]: escaped * does not glob"
for f in \*.txt; do echo "for: $f"; done
echo *.txt
printf '%s\n' \? x\*y
cd /; rm -rf "$d"
