# 2026-10-04: the redirect rewrite. An external child gets the real file handle, and redirects apply
# left to right as dup2 applies them. Lines 1-4, 5, 10, 11, 13 and 21 were wrong before it (found
# while building it). Expected output generated by GNU bash (WSL).
cd "$(mktemp -d)" || exit 1
ext()  { "$BASH" -c 'echo "$1"' _ "$1"; }                 # a real external process in both shells
both() { "$BASH" -c 'echo "out:$1"; echo "err:$1" >&2' _ "$1"; }

# where the output goes: the newest installation wins over a pipeline stage's pipe
echo "1 [$(ext captured)]" | cat
{ ext to-file; } > f1 | cat; echo "2 file: [$(cat f1)]"
for i in 1; do x=$(ext in-loop); echo "3 [$x]"; done | cat
printf 'a\nb\nc\n' | { read -r first; echo "4 read: $first"; "$BASH" -c cat; }

# left to right
both A 2>&1 >f2 | sed 's/^/5 piped: /'; echo "5 f2: [$(cat f2)]"
both B >f3 2>&1; echo "6 f3: [$(sort f3 | tr '\n' ' ')]"
both C 2>f4 >&2; echo "7 f4: [$(sort f4 | tr '\n' ' ')]"
both D &>f5; echo "8 f5: [$(sort f5 | tr '\n' ' ')]"
both E &>>f5; echo "9 f5 lines: $(wc -l < f5)"

# appenders interleave instead of overwriting each other (unrolled: a loop variable read by a
# background job is the separate open item "background jobs share the parent's variables")
w='for j in 1 2 3 4 5 6 7 8 9 10; do echo "w$1 $j"; done'
"$BASH" -c "$w" _ 1 >> f6 & "$BASH" -c "$w" _ 2 >> f6 & "$BASH" -c "$w" _ 3 >> f6 & wait
echo "10 appended lines: $(wc -l < f6), distinct: $(sort -u f6 | wc -l)"

# a log can be read while its writer runs
"$BASH" -c 'echo first; sleep 1; echo second' > f7 & sleep 0.5; echo "11 while running: [$(cat f7)]"; wait
echo "12 after: [$(tr '\n' ' ' < f7)]"

# the shell's own redirect, shared with a child, keeps the order
{ echo a; ext b; echo c; } > f8; echo "13 order: [$(tr '\n' ' ' < f8)]"

# /dev/null, here-string, <>
ext null > /dev/null; echo "14 status $?"
"$BASH" -c 'cat' <<< "15 here-string"
echo "16 rw" > f9; "$BASH" -c 'cat' <> f9

# errors: the command does not run
{ ext x > /no/such/dir/f; } 2>/dev/null; echo "17 bad target: $?"
ext x 2>/dev/null > /no/such/dir/f; echo "18 an earlier 2>/dev/null silences it: $?"
set -C; echo keep > f10; { ext clobber > f10; } 2>/dev/null; echo "19 noclobber: $? [$(cat f10)]"
ext forced >| f10; echo "20 >|: [$(cat f10)]"; set +C

# an in-process redirect failure fails that one command, reported where stderr points then
{ echo x > /no/such/dir/f; echo "22 the group carries on: $?"; } 2>/dev/null
fn() { echo in-fn; }; fn 2>/dev/null > /no/such/dir/f; echo "23 function, earlier 2>/dev/null: $?"

# a script run in-process takes its redirects and VAR=x
printf '#!/bin/bash\necho "out FOO=$FOO"\necho err >&2\n' > s.sh; chmod +x s.sh
FOO=tmp ./s.sh > s.out 2> s.err; echo "21 script: [$(cat s.out)] [$(cat s.err)]"
./s.sh 2>/dev/null | tr a-z A-Z
