# 2026-10-04 (reported by nupkg-28): a function named after a builtin utility was never called --
# the utility ran instead, while `type -t` said "function". A helper `rev(){ hg log ...; }` silently
# returned "" and a script went on to update to the wrong revision. Bash's order is function,
# builtin, PATH. Expected output generated by GNU bash (WSL).
rev() { echo "rev-function"; }
rev </dev/null
echo "[$(rev)]"
echo abc | rev
type -t rev
command rev <<< "abc"
unset -f rev
echo abc | rev

cat() { echo "cat-function: $*"; }
cat a b </dev/null
echo "[$( sort(){ echo sort-function; }; sort </dev/null )]"
unset -f cat

# a wrapper that calls through to the real thing
ls() { echo "wrapped ls:"; command ls "$@"; }
ls -d /
echo() { builtin echo "<$*>"; }
echo shadowed echo
unset -f echo ls
echo plain again

# a function shadowing a builtin is found from inside another function and a pipeline stage
wc() { builtin echo "wc-function"; }
f() { wc -l; }
printf 'x\ny\n' | f
printf 'x\n' | wc | tr a-z A-Z
unset -f wc f
printf 'x\ny\n' | wc -l
