# 2026-10-05: jq error messages, parse errors, number formats and edge behaviour, measured against
# jq 1.6 (expected output generated by it). Probes from building the in-process subset.
cd "$(mktemp -d)" || exit 1
p() { printf '%s => ' "$1"; shift; "$@" 2>&1 | tr '\n' '|'; echo; }
p 'from_entries name'   jq -c 'from_entries' <<< '[{"name":"a","value":1}]'
p 'from_entries k/v'    jq -c 'from_entries' <<< '[{"k":"a","v":1}]'
p 'from_entries Key/Value' jq -c 'from_entries' <<< '[{"Key":"a","Value":1}]'
p 'from_entries K/V'    jq -c 'from_entries' <<< '[{"K":"a","V":1}]'
p 'from_entries Name'   jq -c 'from_entries' <<< '[{"Name":"a","value":1}]'
p 'from_entries numkey' jq -c 'from_entries' <<< '[{"key":1,"value":1}]'
p 'from_entries false'  jq -c 'from_entries' <<< '[{"key":false,"value":1}]'
p 'from_entries novalue' jq -c 'from_entries' <<< '[{"key":"a"}]'
p 'idx num str'    jq '.a' <<< '5'
p 'idx arr str'    jq '.a' <<< '[1]'
p 'idx obj num'    jq '.[0]' <<< '{}'
p 'idx str num'    jq '.[0]' <<< '"s"'
p 'idx bool'       jq '.a' <<< 'true'
p 'iterate str'    jq '.[]' <<< '"abc"'
p 'iterate long'   jq '.[]' <<< '"abcdefghijklmnopqrstuvwxyz"'
p 'add long'       jq '. + 1' <<< '{"aaaaaaaa":1,"bbbbbbbb":2}'
p 'keys num'       jq 'keys' <<< '5'
p 'has err'        jq 'has(0)' <<< '{}'
p 'length bool'    jq 'length' <<< 'true'
p 'div runtime'    jq '. / 0' <<< '1'
p 'mod runtime'    jq '. % 0' <<< '1'
p 'mod literal'    jq '1 % 0' <<< 'null'
p 'str * 1.5'      jq -c '["ab" * 1.5, "ab" * 0.5, "ab" * 0, "ab" * -1]' <<< 'null'
p 'neg zero'       jq -c '[-0, 0 * -1, (-0 | tostring), -0.0]' <<< 'null'
p 'alt error'      jq -c '(.a.b // 5)' <<< '{"a":3}'
p 'alt err 2'      jq -c '[.[] | (.x // "d")]' <<< '[1, {"x":2}]'
p 'parse tru'      jq '.' <<< 'tru'
p 'parse obj'      jq '.' <<< '{"a" 1}'
p 'parse comma'    jq '.' <<< '[1,]'
p 'parse num'      jq '.' <<< '1.2.3'
p 'parse eof str'  jq '.' <<< '"abc'
p 'parse 2nd line' jq -c '.' <<< $'{"a":1}\n{"b":'
p 'syntax unexpected ident'  jq '.a b' <<< null
p 'syntax bad char' jq '.a $' <<< null
p 'syntax paren'   jq '(.a' <<< null
p 'undefined fn'   jq 'foo' <<< null
p 'undefined var'  jq '$x' <<< null
p 'error null'     jq 'error(null)' <<< null
p 'error num'      jq 'error(1)' <<< null
p 'tonumber bad'   jq 'tonumber' <<< '"abc"'
p 'fromjson bad'   jq 'fromjson' <<< '"{a"'
p 'csv bad'        jq -r '@csv' <<< '[[1]]'
p 'test non-str'   jq 'test("a")' <<< '1'
p 'loc multi'      jq '.a.b' <<< $'1\n2\n{"a":5}\n'
p 'fe v'          jq -c 'from_entries' <<< '[{"key":"a","v":1}]'
p 'fe value false' jq -c 'from_entries' <<< '[{"key":"a","value":false}]'
p 'fe Value+value' jq -c 'from_entries' <<< '[{"key":"a","Value":2,"value":3}]'
p 'fe key null name' jq -c 'from_entries' <<< '[{"key":null,"name":"x","value":1}]'
p 'fe empty'      jq -c 'from_entries' <<< '[]'
p 'syntax then'   jq '.a then' <<< null
p 'syntax ]'      jq '.a]' <<< null
p 'syntax ,'      jq ',' <<< null
p 'syntax str'    jq '.a "x"' <<< null
p 'syntax num'    jq '.a 1' <<< null
p 'syntax eq'     jq '.a == == 1' <<< null
p 'syntax multi'  jq $'.a\n| .b |' <<< null
p 'undefined arity' jq 'map' <<< null
p 'undefined mid' jq '.a | foo(1)' <<< null
p 'unclosed str'  jq '"abc' <<< null
p 'parse obj trailing comma' jq . <<< '{"a":1,}'
p 'parse lone ]'  jq . <<< ']'
p 'parse colon'   jq . <<< '{"a":1:2}'
p 'parse key num' jq . <<< '{1:2}'
p 'parse tru eof' "$BASH" -c "printf 'tru' | jq ."
p 'parse ok then bad' "$BASH" -c "printf '1 2 x' | jq -c ."
p 'error str nl' jq 'error("a\nb")' <<< null
p 'big int'       jq -c '.' <<< '[12345678901234567890, 1.7976931348623157e308, 5e-324, 100000000000000000]'
p 'div mod neg'   jq -c '[-7 % 2, 7 % -2, 5.9 % 2, (1 / 3)]' <<< null
