# 2026-10-03: the pattern of ${x#pat} ${x##pat} ${x%pat} ${x%%pat} ${x/pat/rep} ${x//pat/rep}
# (and the replacement) was used RAW: an expansion or a quote in it was never processed, so
# `${p#"$prefix"}`, `${p//$o/$n}` and even `${p%%"/z"}` silently returned the input. Expected
# output generated by GNU bash (WSL Ubuntu).
p=/x/y/z.tar.gz; s=/x; suf=.gz; o=y; n=Q
echo "1 ${p#"$s"/} | ${p#$s/} | ${p#/x/}"
echo "2 ${p%"$suf"} | ${p%$suf} | ${p%%.*} | ${p%%"/z.tar.gz"}"
echo "3 ${p/$o/$n} | ${p//"/"/_} | ${p/#"$s"/ROOT} | ${p/%"$suf"/.bz2}"
star='*'; lit='a*b'
echo "4 quoted var is literal: ${lit#"$star"} | unquoted var is a pattern: ${lit#$star}"
echo "5 escaped glob in pattern: ${lit#a\*} | quoted glob: ${lit#"a*"} | live glob: ${lit#a*}"
v='a\b\c'; echo "6 backslashes: ${v//\\/\/} | ${v//'\'/-}"
V=aab; echo "7 replacement escapes: ${V//b/\\} | ${V//a/\$} | ${V//a/"\$x"}"
d=dir; echo "8 command subst in pattern: ${p#$(echo /x)} | arith: ${p:$((1+1))}"
f=$HOME/notes.txt; echo "9 tilde: ${f#~/}"
arr=(/x/a /x/b /y/c); echo "10 arrays: ${arr[@]#"$s"/}"
x="hello world"; w=world; echo "11 spaces: ${x% "$w"} | ${x/ $w/!}"
echo "12 slash inside quotes: ${p//"/x"/[X]} | empty rep: ${p/"/x"}"
