# 2026-10-03: every pipeline stage runs in its own subshell, as in bash. Stages used to share the
# shell's state on their threads: `echo x | read v` left v=x, a `| while read` counter survived,
# and a `$( )` in one stage could restore its snapshot over another stage's $1 or lose its output.
# Expected output generated by GNU bash (WSL Ubuntu). The cwd is NOT covered (still process-wide).
v=unset; echo x | read v; echo "read in a stage: [$v]"
n=0; printf '1\n2\n3\n' | while read -r l; do n=$((n+1)); done; echo "while-read counter after: $n"
g=parent; f() { echo "f sees g=$g, \$1=$1"; }
echo | { f arg; g=stage; h() { :; }; export E=1; }
echo "after: g=$g, h defined: $(declare -F h >/dev/null && echo yes || echo no), E=[${E-}]"
arr=(a b c); declare -A m=([k]=v)
echo | { echo "stage sees: ${arr[1]} ${m[k]} ${#arr[@]}"; arr[1]=Z; m[k]=Z; }
echo "parent keeps: ${arr[1]} ${m[k]}"
set -- p1 p2
echo | { echo "stage \$#=$# \$1=$1"; set -- q; }
echo "parent \$#=$# \$1=$1"
echo | { exit 3; }; echo "after exit in a stage: status $?, still running"
true | (exit 4) | false; echo "PIPESTATUS: ${PIPESTATUS[*]}"
x=1; { x=2; echo "$x"; } | { read -r y; echo "sibling got $y, own x=$x"; }; echo "parent x=$x"
alias ll='echo aliased'; echo | { unalias ll 2>/dev/null; }; alias ll >/dev/null 2>&1 && echo "alias survives" || echo "alias gone"
f2() { echo "arg=$1"; }
for i in 1 2 3; do printf '%s\n' "$i" | { read -r a; f2 "$a"; }; done
