# 2026-10-05: three defects peers hit.
# 1. sed/grep basic regex: `$`/`^` are anchors only at the ends (or by `\(` `\)` `\|`); elsewhere
#    literals. A leading `*` is a literal (in -E too). daq-67: `s|^REV=$(hg id -n)$|..|` matched nothing.
# 2. grep -P `\K` (koliada-net-dd): "Unrecognized escape sequence \K".
# 3. `diff -` did not read stdin. Expected output generated by GNU bash + coreutils (WSL).
cd "$(mktemp -d)" || exit 1

echo 'REV=$(hg id -n)' | sed 's|^REV=$(hg id -n)$|REV=42|'
echo 'S=$1 x'  | sed 's/^S=$1/M/'
echo 'a^b'     | sed 's/a^b/M/'
echo 'ab'      | sed 's/\(b$\)/M/'
echo 'ab'      | sed 's/\(^a\)/M/'
echo 'ab'      | sed 's/x\|^a/M/'
echo 'ab'      | sed 's/b$\|x/M/'
echo 'a*b'     | sed 's/*b/M/'
echo '*ab'     | sed 's/^*a/M/'
echo 'a*b'     | sed 's/a\(*\)b/M/'
echo 'x$1y'    | grep -c 'x$1'
echo 'a^b'     | grep -c 'a^b'
echo 'a$b'     | grep -cE 'a$b'
echo 'a$b'     | grep -cE 'a\$b'
echo 'a*b'     | grep -cE '*b'
echo 'a^b'     | sed -E 's/a^b/M/'

printf 'public void Alpha()\npublic void Beta()\nprivate int Gamma()\n' > k.txt
grep -oP 'public void \K\w+(?=\(\))' k.txt
grep -oP 'void \Kpublic|\w+ \K\w+' k.txt 2>/dev/null; echo "top-level | with \\K: $?"
grep -oP '(?:public|private) \w+ \K\w+' k.txt
grep -oP 'pub\Klic void \K\w+' k.txt
grep -cP 'Al\Kpha' k.txt

printf 'a\nb\nc\n' > f1
printf 'a\nB\nc\n' | diff f1 -; echo "diff f1 -: $?"
printf 'a\nb\nc\n' | diff - f1; echo "identical: $?"
printf 'x\n' | diff -q - f1; echo "diff -q: $?"
