# 2026-10-03: commands sharing one stdin. A text reader (read, head -n, grep) reads ahead into
# the shell's LfReader; a byte builtin (cat, od, wc -c) that followed started past that and the
# rest was lost -- `{ read -r header; cat; } < f` printed nothing. And head -c read ALL of its
# input before taking N bytes: `yes | head -c 5` never finished, and `{ head -c 2; read x; } < f`
# left nothing for read. Expected output generated by GNU bash + coreutils (WSL Ubuntu).
d=$(mktemp -d)
cd "$d" || exit 1
printf 'a\nb\r\nc\n\377d\n' > f.txt
p() { printf '%-28s' "$1"; od -An -c | tr -s ' ' | tr -d '\n'; echo; }
{ read -r x; cat; } < f.txt                      | p 'read;cat < f'
{ head -n 1; cat; } < f.txt                      | p 'head;cat < f'
{ read -r x; read -r y; cat; } < f.txt           | p 'read;read;cat < f'
{ read -r x; od -An -c; } < f.txt                | p 'read;od < f'
{ read -r x; wc -c; } < f.txt                    | p 'read;wc -c < f'
{ grep -m1 a; cat; } < f.txt                     | p 'grep -m1;cat < f'
cat f.txt | { read -r x; cat; }                  | p 'pipe: read;cat'
{ head -c 2; echo; read -r x; echo "[$x]"; } < f.txt | p 'head -c;read < f'
timeout 10 "$BASH" -c 'yes | head -c 5'          | p 'yes|head -c 5'
cd / && rm -rf "$d"
