# 2026-10-04 (reported by nupkg-28): a function defined in `( )` or `$( )` leaked into the
# parent shell. Once rev 106 let a function shadow a builtin, a `rev` defined inside one `$( )`
# replaced the utility for the rest of the script. A subshell gets a COPY of the function table.
# Expected output generated by GNU bash (WSL).
x=$( leak1() { echo LEAK; }; leak1 ); echo "inside \$( ) it runs: [$x]"
echo "after \$( ): [$(type -t leak1)]"
( leak2() { echo LEAK; }; leak2 ); echo "after ( ): [$(type -t leak2)]"
cat <( leak3() { echo LEAK; }; leak3 ) ; echo "after <( ): [$(type -t leak3)]"
y=$( rev() { echo FUNC; }; true ); echo "rev is the utility again: [$(echo abc | rev)]"

keep() { echo original; }
( keep() { echo replaced; }; keep ); keep
( unset -f keep; type -t keep || echo "unset inside" ); keep
z=$( unset -f keep ); keep

# nested: each level keeps its own changes
( a() { echo a1; }; ( a() { echo a2; }; a ); a ); echo "outer: [$(type -t a)]"
( b() { echo b1; }; x=$( b() { echo b2; }; b ); echo "inner said $x"; b )

# a definition at top level after subshells still sticks
late() { echo late; }; late
