# 2026-10-04: options, shopts, traps and aliases set inside ( ), $( ) or <( ) leaked into the
# parent shell (functions were fixed in rev 109; this is the rest of the class). In bash a
# subshell is a copy: nothing it sets comes back, and an EXIT trap it sets fires as IT ends.
# Expected output generated by GNU bash (WSL).
( set -e ); echo "after ( set -e ): [${-//[^e]/}]"
x=$( set -u ); echo "after \$( set -u ): [${-//[^u]/}]"
( set -o pipefail ); [[ -o pipefail ]] && echo "pipefail leaked" || echo "pipefail isolated"
cat <( set -f ) >/dev/null; echo "after <( set -f ): [${-//[^f]/}]"
( shopt -s nullglob ); shopt -q nullglob && echo "nullglob leaked" || echo "nullglob isolated"
x=$( shopt -s dotglob ); shopt -q dotglob && echo "dotglob leaked" || echo "dotglob isolated"

# options set in the parent are still seen inside, and survive the subshell
set -o pipefail
( [[ -o pipefail ]] && echo "inside: pipefail inherited" ); [[ -o pipefail ]] && echo "parent: pipefail kept"
set +o pipefail

# traps
( trap 'echo "subshell EXIT trap"' EXIT; echo "in subshell" ); echo "after: [$(trap -p EXIT)]"
x=$( trap 'echo captured-trap' EXIT; echo body ); echo "captured: [${x//$'\n'/|}]"
( trap 'echo "trap then exit 3"; exit 3' EXIT; true ); echo "status from trap: $?"
( trap 'echo "fires once"' EXIT; exit 5 ); echo "status: $?"
( ( trap 'echo inner-trap' EXIT ); echo "outer continues" )
trap 'echo "PARENT EXIT trap"' EXIT
( echo "subshell does not run the parent's trap" )
x=$( trap 'echo replaced' EXIT ); echo "parent trap kept: [$(trap -p EXIT)]"

# aliases
shopt -s expand_aliases
( alias zz='echo ALIAS' ); alias zz >/dev/null 2>&1 && echo "alias leaked" || echo "alias isolated"
alias yy='echo yy-alias'
( unalias yy ); alias yy >/dev/null 2>&1 && echo "alias survives unalias in ( )"
echo "end of script"
