# 2026-10-04: `time` is a reserved word timing a whole pipeline; C#Bash had none ("time: command
# not found"), which pushed 37 transcript calls to PowerShell's Measure-Command. Times vary, so
# every report is captured and its digits masked. Expected output generated by GNU bash (WSL).
m() { sed 's/[0-9]/N/g'; }
{ time true; } 2>&1 | m
{ time -p true; } 2>&1 | m
TIMEFORMAT='took %0R s'
{ time sleep 0.1; } 2>&1
{ time echo through-a-pipe | cat; } 2>&1
{ time { echo in-a-group; true; }; } 2>&1
{ time false; } 2>&1; echo "status kept: $?"
{ time ! false; } 2>&1; echo "negated: $?"
{ time ls /no/such/dir 2>/dev/null; } 2>&1; echo "the command's own 2>/dev/null does not hide the report"
TIMEFORMAT='%3R|%2U|%1S|%0lR|%lR|%%' ; { time true; } 2>&1 | m
TIMEFORMAT='%P' ; { time true; } 2>&1 | sed 's/[0-9]\+/N/g'
TIMEFORMAT=''; { time true; } 2>&1; echo "empty TIMEFORMAT: no report"
unset TIMEFORMAT
x=$( { time true; } 2>&1 >/dev/null | m ); echo "captured: [${x//$'\n'/|}]"
