using System.Globalization;
using System.Text;

namespace Bash.Evaluator;

// ── jq's values (DECISIONS 2026-10-05, the in-process jq subset) ─────────────────────────
// A JSON value is a CLR object: null, bool, double, string, JArr (List<object?>) or JObj. Values
// are never mutated once built; an assignment copies the containers along its path. Printing and
// parsing are ports of jq 1.6 (jv_print.c, jv_dtoa.c's jvp_dtoa_fmt, jv_parse.c), checked against
// jq 1.6 itself (tests/cases/jq_subset.sh, expected output generated by it).

/// <summary>A JSON object that keeps its keys in insertion order, as jq prints them.</summary>
internal sealed class JObj
	{
	private readonly Dictionary<string, object?> _map = new(StringComparer.Ordinal);
	private readonly List<string> _order = [];

	public int Count => _order.Count;
	public IReadOnlyList<string> Keys => _order;
	public bool ContainsKey(string k) => _map.ContainsKey(k);
	public bool TryGet(string k, out object? v) => _map.TryGetValue(k, out v);
	public object? Get(string k) => _map.TryGetValue(k, out var v) ? v : null;

	/// <summary>Set (a new key goes last, an existing one keeps its place). Only while building.</summary>
	public void Set(string k, object? v)
		{
		if (!_map.ContainsKey(k)) _order.Add(k);
		_map[k] = v;
		}

	public void Remove(string k) { if (_map.Remove(k)) _order.Remove(k); }

	public JObj Copy()
		{
		var o = new JObj();
		foreach (var k in _order) o.Set(k, _map[k]);
		return o;
		}

	public IEnumerable<KeyValuePair<string, object?>> Pairs()
		{
		foreach (var k in _order) yield return new(k, _map[k]);
		}
	}

/// <summary>A jq runtime error. It carries a VALUE (usually a message string), as `error(v)` does.</summary>
internal sealed class JqError(object? value) : Exception(value as string ?? Json.Dump(value, compact: true))
	{
	public object? Value { get; } = value;
	}

/// <summary>Reading, printing, ordering and describing JSON values the way jq 1.6 does.</summary>
internal static class Json
	{
	// ── type names and jq's order: null < false < true < numbers < strings < arrays < objects ──

	public static string TypeName(object? v) => v switch
		{
		null => "null", bool => "boolean", double => "number", string => "string",
		List<object?> => "array", JObj => "object", _ => "null",
		};

	private static int Rank(object? v) => v switch
		{
		null => 0, bool b => b ? 2 : 1, double => 3, string => 4, List<object?> => 5, JObj => 6, _ => 0,
		};

	public static int Compare(object? a, object? b)
		{
		int ra = Rank(a), rb = Rank(b);
		if (ra != rb) return ra.CompareTo(rb);
		switch (a)
			{
			case double x: return x.CompareTo((double)b!);
			case string s: return string.CompareOrdinal(s, (string)b!);
			case List<object?> la:
				{
				var lb = (List<object?>)b!;
				for (int i = 0; i < la.Count && i < lb.Count; i++)
					{
					int c = Compare(la[i], lb[i]);
					if (c != 0) return c;
					}
				return la.Count.CompareTo(lb.Count);
				}
			case JObj oa:
				{
				// keys first (as sorted arrays), then the values in sorted-key order
				var ob = (JObj)b!;
				var ka = SortedKeys(oa); var kb = SortedKeys(ob);
				for (int i = 0; i < ka.Count && i < kb.Count; i++)
					{
					int c = string.CompareOrdinal(ka[i], kb[i]);
					if (c != 0) return c;
					}
				if (ka.Count != kb.Count) return ka.Count.CompareTo(kb.Count);
				foreach (var k in ka)
					{
					int c = Compare(oa.Get(k), ob.Get(k));
					if (c != 0) return c;
					}
				return 0;
				}
			default: return 0;   // null, or booleans of the same rank
			}
		}

	public static bool Equal(object? a, object? b) => Compare(a, b) == 0;

	public static bool Truthy(object? v) => v is not null && v is not false;

	public static List<string> SortedKeys(JObj o)
		{
		var keys = new List<string>(o.Keys);
		keys.Sort(string.CompareOrdinal);
		return keys;
		}

	// ── printing ──────────────────────────────────────────────────────────────────────────────

	public static string Dump(object? v, bool compact, int indent = 2, bool sortKeys = false, bool ascii = false)
		{
		var sb = new StringBuilder();
		Write(sb, v, compact, indent, 0, sortKeys, ascii);
		return sb.ToString();
		}

	public static void Write(StringBuilder sb, object? v, bool compact, int indent, int level, bool sortKeys, bool ascii)
		{
		switch (v)
			{
			case null: sb.Append("null"); break;
			case bool b: sb.Append(b ? "true" : "false"); break;
			case double d: sb.Append(Number(d)); break;
			case string s: Quote(sb, s, ascii); break;
			case List<object?> arr:
				if (arr.Count == 0) { sb.Append("[]"); break; }
				sb.Append('[');
				for (int i = 0; i < arr.Count; i++)
					{
					if (i > 0) sb.Append(',');
					if (!compact) NewLine(sb, indent, level + 1);
					Write(sb, arr[i], compact, indent, level + 1, sortKeys, ascii);
					}
				if (!compact) NewLine(sb, indent, level);
				sb.Append(']');
				break;
			case JObj obj:
				if (obj.Count == 0) { sb.Append("{}"); break; }
				sb.Append('{');
				var keys = sortKeys ? SortedKeys(obj) : (IReadOnlyList<string>)obj.Keys;
				for (int i = 0; i < keys.Count; i++)
					{
					if (i > 0) sb.Append(',');
					if (!compact) NewLine(sb, indent, level + 1);
					Quote(sb, keys[i], ascii);
					sb.Append(compact ? ":" : ": ");
					Write(sb, obj.Get(keys[i]), compact, indent, level + 1, sortKeys, ascii);
					}
				if (!compact) NewLine(sb, indent, level);
				sb.Append('}');
				break;
			}
		}

	private static void NewLine(StringBuilder sb, int indent, int level) => sb.Append('\n').Append(' ', indent * level);

	/// <summary>jq 1.6's jvp_dtoa_fmt: the shortest digits that round-trip, printed plainly unless the
	/// decimal point falls more than 15 places past them or before the 4th decimal place, then as
	/// `d.ddde+XX`. So 1e17 prints `1e+17` but 12345678901234567890 prints `12345678901234567000`;
	/// -0 keeps its sign. NaN prints null, infinities clamp to ±DBL_MAX.</summary>
	public static string Number(double d)
		{
		if (double.IsNaN(d)) return "null";
		if (double.IsPositiveInfinity(d)) d = double.MaxValue;
		if (double.IsNegativeInfinity(d)) d = -double.MaxValue;
		var sign = double.IsNegative(d) ? "-" : "";
		if (d == 0) return sign + "0";
		// shortest round-trip digits and the decimal point's position (decpt), as dtoa mode 0 gives
		var r = Math.Abs(d).ToString("R", CultureInfo.InvariantCulture);
		int e = r.IndexOf('E');
		int exp = e < 0 ? 0 : int.Parse(r[(e + 1)..], CultureInfo.InvariantCulture);
		var mant = e < 0 ? r : r[..e];
		int dot = mant.IndexOf('.');
		var digits = dot < 0 ? mant : mant.Remove(dot, 1);
		int decpt = (dot < 0 ? mant.Length : dot) + exp;
		int lead = 0;
		while (lead < digits.Length - 1 && digits[lead] == '0') lead++;
		digits = digits[lead..]; decpt -= lead;
		digits = digits.TrimEnd('0');
		if (digits.Length == 0) digits = "0";
		var sb = new StringBuilder(sign);
		if (decpt <= -4 || decpt > digits.Length + 15)
			{
			sb.Append(digits[0]);
			if (digits.Length > 1) sb.Append('.').Append(digits, 1, digits.Length - 1);
			int x = decpt - 1;
			sb.Append('e').Append(x < 0 ? '-' : '+').Append(Math.Abs(x).ToString("00", CultureInfo.InvariantCulture));
			}
		else if (decpt <= 0) sb.Append("0.").Append('0', -decpt).Append(digits);
		else if (decpt >= digits.Length) sb.Append(digits).Append('0', decpt - digits.Length);
		else sb.Append(digits, 0, decpt).Append('.').Append(digits, decpt, digits.Length - decpt);
		return sb.ToString();
		}

	public static void Quote(StringBuilder sb, string s, bool ascii)
		{
		sb.Append('"');
		foreach (char c in s)
			{
			switch (c)
				{
				case '"':  sb.Append("\\\""); break;
				case '\\': sb.Append("\\\\"); break;
				case '\n': sb.Append("\\n"); break;
				case '\t': sb.Append("\\t"); break;
				case '\r': sb.Append("\\r"); break;
				case '\b': sb.Append("\\b"); break;
				case '\f': sb.Append("\\f"); break;
				default:
					if (c < 0x20 || c == 0x7f || (ascii && c > 0x7e)) sb.Append("\\u").Append(((int)c).ToString("x4", CultureInfo.InvariantCulture));
					else sb.Append(c);
					break;
				}
			}
		sb.Append('"');
		}

	/// <summary>A value as jq quotes it inside an error message (jv_dump_string_trunc into 15
	/// bytes): compact JSON, and when it is longer than 14 characters its first 11 and "...".</summary>
	public static string Brief(object? v)
		{
		var s = Dump(v, compact: true);
		return s.Length > 14 ? s[..11] + "..." : s;
		}

	// ── reading: a port of jq 1.6's jv_parse.c ──────────────────────────────────────────────────

	public sealed class ParseException(string message) : Exception(message);

	/// <summary>Every JSON value in <paramref name="text"/> with the location jq reports for it: the
	/// number of input lines read when the value completed (jq reads its input a line at a time).
	/// A parse error ends the stream with jq's message and position.</summary>
	public static IEnumerable<(object? Value, int Line)> Stream(string text) => new StreamParser(text).Run();

	public static IEnumerable<object?> ParseAll(string text) => Stream(text).Select(x => x.Value);

	/// <summary>Exactly one value (fromjson, tonumber, --argjson).</summary>
	public static object? ParseOne(string text)
		{
		var all = ParseAll(text).Take(2).ToList();
		if (all.Count != 1) throw new ParseException(all.Count == 0 ? "Expected JSON value" : "Unexpected extra JSON values");
		return all[0];
		}

	private sealed class StreamParser(string s)
		{
		private int _line = 1, _col;
		private readonly List<object?> _stack = [];   // arrays and objects, and an object's key (a string) above it
		private object? _next;
		private bool _hasNext;
		private readonly StringBuilder _token = new();
		private readonly StringBuilder _str = new();
		private bool _inString, _escape;

		private ParseException Error(string msg) => new($"{msg} at line {_line}, column {_col}");

		public IEnumerable<(object?, int)> Run()
			{
			int start = s.Length > 0 && s[0] == '﻿' ? 1 : 0;   // a UTF-8 BOM (Windows files) is skipped
			for (int i = start; i < s.Length; i++)
				{
				char ch = s[i];
				_col++;
				if (ch == '\n') { _line++; _col = 0; }
				if (_inString)
					{
					if (_escape) { _str.Append(ch); _escape = false; continue; }
					if (ch == '\\') { _str.Append(ch); _escape = true; continue; }
					if (ch != '"') { _str.Append(ch); continue; }
					_inString = false;
					Value(Unescape());
					if (Done(out var v)) yield return (v, LinesRead(i));
					continue;
					}
				switch (ch)
					{
					case ' ' or '\t' or '\r' or '\n':
						CheckLiteral(atEof: false);
						break;
					case '[' or ',' or ']' or '{' or ':' or '}':
						CheckLiteral(atEof: false);
						Token(ch);
						break;
					case '"':
						CheckLiteral(atEof: false);
						_inString = true; _str.Clear();
						break;
					default:
						_token.Append(ch);
						continue;
					}
				if (Done(out var w)) yield return (w, LinesRead(i));
				}
			if (_inString) throw new ParseException($"Unfinished string at EOF at line {_line}, column {_col}");
			try { CheckLiteral(atEof: true); }
			catch (ParseException e) { throw new ParseException(e.Message.Replace(" at line ", " at EOF at line ")); }
			if (_stack.Count > 0) throw new ParseException($"Unfinished JSON term at EOF at line {_line}, column {_col}");
			if (Done(out var last)) yield return (last, s.Count(c => c == '\n'));
			}

		/// <summary>jq reads with fgets: the lines read once the value completes at index i include the
		/// whole line i is on, counted only if it ends in a newline.</summary>
		private int LinesRead(int i)
			{
			// _line - 1 newlines have been consumed through index i
			if (s[i] == '\n') return _line - 1;
			return _line - 1 + (s.IndexOf('\n', i) >= 0 ? 1 : 0);
			}

		private bool Done(out object? v)
			{
			v = null;
			if (_stack.Count != 0 || !_hasNext) return false;
			v = _next; _next = null; _hasNext = false;
			return true;
			}

		private void Value(object? v)
			{
			if (_hasNext) throw Error("Expected separator between values");
			_next = v; _hasNext = true;
			}

		private void CheckLiteral(bool atEof)
			{
			if (_token.Length == 0) return;
			var t = _token.ToString();
			_token.Clear();
			string? pattern = t[0] switch { 't' => "true", 'f' => "false", 'n' => "null", _ => null };
			if (pattern is not null)
				{
				if (t != pattern) throw Error("Invalid literal");
				Value(pattern == "null" ? null : pattern == "true");
				return;
				}
			bool numeric = t.All(c => char.IsAsciiDigit(c) || c is '-' or '+' or '.' or 'e' or 'E');
			if (!numeric || !double.TryParse(t, NumberStyles.Float, CultureInfo.InvariantCulture, out var d))
				throw Error("Invalid numeric literal");
			Value(d);
			}

		private void Token(char ch)
			{
			int top = _stack.Count - 1;
			switch (ch)
				{
				case '[':
					if (_hasNext) throw Error("Expected separator between values");
					_stack.Add(new List<object?>());
					break;
				case '{':
					if (_hasNext) throw Error("Expected separator between values");
					_stack.Add(new JObj());
					break;
				case ':':
					if (top < 0 || _stack[top] is not JObj) throw Error("':' not as part of an object");
					if (!_hasNext) throw Error("Expected string key before ':'");
					if (_next is not string key) throw Error("Object keys must be strings");
					_stack.Add(key);
					_next = null; _hasNext = false;
					break;
				case ',':
					if (!_hasNext) throw Error("Expected value before ','");
					if (top < 0) throw Error("',' not as part of an object or array");
					if (_stack[top] is List<object?> arr) { arr.Add(_next); _next = null; _hasNext = false; }
					else if (_stack[top] is string k) { ((JObj)_stack[top - 1]!).Set(k, _next); _stack.RemoveAt(top); _next = null; _hasNext = false; }
					else throw Error("Objects must consist of key:value pairs");
					break;
				case ']':
					if (top < 0 || _stack[top] is not List<object?> a) throw Error("Unmatched ']'");
					if (_hasNext) { a.Add(_next); }
					else if (a.Count != 0) throw Error("Expected another array element");
					_next = a; _hasNext = true;
					_stack.RemoveAt(top);
					break;
				case '}':
					if (top < 0) throw Error("Unmatched '}'");
					if (_hasNext)
						{
						if (_stack[top] is not string k2) throw Error("Objects must consist of key:value pairs");
						((JObj)_stack[top - 1]!).Set(k2, _next);
						_stack.RemoveAt(top); top--;
						}
					else
						{
						if (_stack[top] is not JObj) throw Error("Unmatched '}'");
						if (((JObj)_stack[top]!).Count != 0) throw Error("Expected another key-value pair");
						}
					_next = _stack[top]; _hasNext = true;
					_stack.RemoveAt(top);
					break;
				}
			}

		/// <summary>The raw text between the quotes, unescaped as jq's found_string does.</summary>
		private string Unescape()
			{
			var raw = _str;
			var sb = new StringBuilder(raw.Length);
			for (int i = 0; i < raw.Length; i++)
				{
				char c = raw[i];
				if (c != '\\') { sb.Append(c); continue; }
				char e = raw[++i];
				switch (e)
					{
					case '"' or '\\' or '/': sb.Append(e); break;
					case 'b': sb.Append('\b'); break;
					case 'f': sb.Append('\f'); break;
					case 'n': sb.Append('\n'); break;
					case 'r': sb.Append('\r'); break;
					case 't': sb.Append('\t'); break;
					case 'u':
						if (i + 4 >= raw.Length) throw Error("Invalid \\uXXXX escape");
						var hex = raw.ToString(i + 1, 4);
						if (!int.TryParse(hex, NumberStyles.HexNumber, CultureInfo.InvariantCulture, out int u))
							throw Error("Invalid characters in \\uXXXX escape");
						sb.Append((char)u);
						i += 4;
						break;
					default: throw Error("Invalid escape");
					}
				}
			return sb.ToString();
			}
		}
	}
